import { envs } from "../../config/env";
import { GenerateGuestPassRequest } from "../dtos/ruckus";
import { RuckusGuestPassGenerateRequest, Wlan, Zone } from "../dtos/ruckus/guestpass";

export class GuestPass {

    private readonly domainId: string = ''
    private readonly wlan: Wlan = {
        id: '',
        name: ''
    }
    private readonly zone: Zone = {
        id: '',
        name: ''
    }


    public toRuckusGuestPassGenerateRequest(req: GenerateGuestPassRequest) {
        return {
            domainId: this.domainId,
            guestName: req.guestName,
            wlan: this.wlan,
            zone: this.zone,
            numberOfPasses: req.numberOfPasses,
            passValidFor: {
                expirationValue: 4,
	            expirationUnit: 'HOUR'
            },
            autoGeneratedPassword: true,
            passEffectSince: 'FIRST_USE',
            passUseDays: 1,
            maxDevices: {
                maxDevicesAllowed: 'LIMITED',
	            maxDevicesNumber: 3
            },
            sessionDuration: {
                requireLoginAgain: true,
	            sessionValue: 4,
	            sessionUnit: 'HOUR'
            },
            remarks: `VMS Created for guest [${req.guestName}]`
        } as RuckusGuestPassGenerateRequest
    }
}