export interface GuestPassGenerateRequest {
    domainId?: string
    guestName: string
    wlan: {
      id?: string
      name?: string
    } | null
    zone: {
      id?: string
      name?: string
    } | null
    numberOfPasses: number
    passValidFor: {
      expirationValue?: number
      expirationUnit?: "HOUR" | "DAY" | "WEEK"
    }
    autoGeneratedPassword?: boolean
    passValue?: string
    passEffectSince: "CREATION_TIME" | "FIRST_USE"
    passUseDays?: number
    maxDevices: {
      maxDevicesAllowed?: "UNLIMITED" | "LIMITED"
      maxDevicesNumber?: number
    }
    sessionDuration?: {
      requireLoginAgain?: boolean
      sessionValue?: number
      sessionUnit?: "MIN" | "HOUR" | "DAY" | "WEEK"
    }
    remarks?: string
  }
  
  export interface GuestPassGenerateResponse {
    id?: string
  }

  export interface GuestPassListParameters {
    // The index of the first entry to be retrieved. Default: 0
    index?: string,
    // The maximum number of entries to be retrieved. Default: 100, Maximum: 1000
    listSize?: string
    // Display created date and time by specified time zone. Default is UTC.
    timeZone?: string
    // filter identity guest pass list by wlan id.
    wlan?: string,
    // filter identity guest pass list by display name.
    displayName?: string,
    // filter identity guest pass list by expiration date and time. The start time of expiration date and time.The format is yyyy-MM-dd HH:mm:ss.
    expirationFrom?: string,
    // filter identity guest pass list by expiration date and time. The end time of expiration date and time.The format is yyyy-MM-dd HH:mm:ss.
    expirationTo?: string,
    //filter identity guest pass list by generated date and time. The start time of generated date and time.The format is yyyy-MM-dd HH:mm:ss.
    generatedTimeFrom?: string,
    // filter identity guest pass list by generated date and time. The end time of generated date and time.The format is yyyy-MM-dd HH:mm:ss.
    generatedTimeTo?: string,
  }

  export interface GuestPassListResponse {
    totalCount?: number
    hasMore?: boolean
    firstIndex?: number
    /**
     * extra information for GuestPass
     */
    extra?: {
      rbacMetadata?: {
        [k: string]: string
      }[]
      [k: string]: unknown
    }
    list?: {
      /**
       * ID of the identity guest pass
       */
      id?: string
      /**
       * user ID of the identity guest pass
       */
      userId?: string
      /**
       * Identifier of the identity guest pass
       */
      key?: string
      /**
       * Guest name of the identity guest pass
       */
      guestName?: string
      /**
       * wlan
       */
      wlan?: {
        id?: string
        name?: string
      } | null
      /**
       * zone
       */
      zone?: {
        id?: string
        name?: string
      } | null
      /**
       * SSID
       */
      ssid?: string
      /**
       * Pass valid for
       */
      passValidFor?: {
        expirationValue?: number
        expirationUnit?: "HOUR" | "DAY" | "WEEK"
      }
      /**
       * max Devices
       */
      maxDevices?: {
        /**
         * Max devices allowed
         */
        maxDevicesAllowed?: "UNLIMITED" | "LIMITED"
        /**
         * max devices number
         */
        maxDevicesNumber?: number
      }
      /**
       * Pass generation
       */
      autoGeneratedPassword?: boolean
      /**
       * Pass effective since
       */
      passEffectSince?: "CREATION_TIME" | "FIRST_USE"
      /**
       * Expire new guest pass if not used within
       */
      passUseDays?: number
      /**
       * Remarks
       */
      remarks?: string
      /**
       * Generated date and time
       */
      generatedOn?: string
      /**
       * Expiration date and time
       */
      expirationDate?: string
      /**
       * Wlan description
       */
      wlanRestrition?: string
      /**
       * session duration
       */
      sessionDuration?: {
        requireLoginAgain?: boolean
        sessionValue?: number
        sessionUnit?: "MIN" | "HOUR" | "DAY" | "WEEK"
      }
      /**
       * identifier of the domain
       */
      domainId?: string
      /**
       * Username who generate this GuestPass
       */
      creatorUsername?: string
      /**
       * Is Disabled
       */
      isDisabled?: string
    }[]
  }
  